name: WallRunPlugin
version: '1.0'
main: com.neteasemc.WallRunPlugin
commands:
  flymode:
    description: Toggle fly mode.
    usage: /<command> [on|off]
    permission: Xueziplugin.flymode

permissions:
  Xueziplugin.flymode:
    description: Allows user to toggle fly mode.
    default: op